### Get all people
GET http://localhost:3001/api/persons

### Get person 2
GET http://localhost:3001/api/persons/2

### Get person 999
GET http://localhost:3001/api/persons/999

### Delete person 628d71056f82f33f201096dd
DELETE http://localhost:3001/api/persons/628d71056f82f33f201096dd

### Add new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "New Lad",
    "number": "01-02-3456789"
}

### Update a person
PUT http://localhost:3001/api/persons/628d113b8ede2a222c64b509
Content-Type: application/json

{
    "name": "Arto Vihavainen",
    "number": "055-1232456"
}
