### Fetch all blogs
GET http://localhost:3003/api/blogs

### Add a blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Hacker news",
    "author": "ycombinator",
    "url": "https://news.ycombinator.com",
    "likes": 0
}
